name = "pat-cms"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cms-database"
database_id = "408f5404-dcfc-45d3-8e90-3b00d0489070"

[[d1_databases]]
binding = "LOCAL_DB"
database_name = "local-cms-database"
database_id = "73c09da0-3c52-4edc-a1a3-1de954dfcdb9"
